### PR TITLE
Capitalize european in 2-reproducibility.typ

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@drupol endeavor is US, endeavour is British.

**Comment by drupol** [comment]
> @drupol endeavor is US, endeavour is British.

I tried to use British english as much as possible.

**Comment by szepeviktor** [comment]
There are two of them
https://github.com/search?q=repo%3Adrupol%2Fmaster-thesis%20endeavor&type=code

**Comment by drupol** [comment]
Fixed !

**Pull request merged**
