### PR TITLE
Add a missing "n"

### PR DESCRIPTION
**Pull request by szepeviktor**
Although "intrisic" is a word.

### CODE REVIEW

**Review by drupol — APPROVED** [review]
Thank you once again !

**Comment by szepeviktor** [comment]
@drupol There are 3 US "favor*"-s. The British spelling is "favour*".

**Comment by drupol** [comment]
Indeed, it needs to be fixed. Do you want to submit another PR ?

**Comment by szepeviktor** [comment]
No.

**Comment by drupol** [comment]
Fixed!

**Pull request merged**
